version: "3.7"

services:

  zenn-preview:
    build: .
    restart: always
    volumes:
      - "zenn-articles:/opt/zenn/articles"
      - "zenn-books:/opt/zenn/books"
      - "zenn-git:/opt/zenn/.git"
      - "user-home:/home/node"
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Tokyo

volumes:
  zenn-articles:
  zenn-books:
  zenn-git:
  user-home:

